# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MaaS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CoreTableView'
  pod 'MMCoreNetworkCallbacks'

end

target 'MaaSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CoreTableView'
  pod 'MMCoreNetworkCallbacks'

end

target 'MaaSExampleTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CoreTableView'
  pod 'MMCoreNetworkCallbacks'

end