# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MaaS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CoreTableView'
  pod 'MMCoreNetworkCallbacks'
  pod 'SDWebImage', :modular_headers => true
  pod 'OnBoardingModule', :path => '/Users/slavaplatonov/Desktop/OnBoardingModule'
  pod 'CoreExtensions', :path => '/Users/slavaplatonov/Desktop/CoreExtensions'

end

target 'MaaSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CoreTableView'
  pod 'MMCoreNetworkCallbacks'
  pod 'SDWebImage', :modular_headers => true
  pod 'OnBoardingModule', :path => '/Users/slavaplatonov/Desktop/OnBoardingModule'
  pod 'CoreExtensions', :path => '/Users/slavaplatonov/Desktop/CoreExtensions'

end

target 'MaaSTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CoreTableView'
  pod 'MMCoreNetworkCallbacks'
  pod 'SDWebImage', :modular_headers => true
  pod 'OnBoardingModule', :path => '/Users/slavaplatonov/Desktop/OnBoardingModule'
  pod 'CoreExtensions', :path => '/Users/slavaplatonov/Desktop/CoreExtensions'

end
